### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by miguelwon** [dice-group/AGDISTIS_DEMO#2]
Hi,

[Demo](http://agdistis.aksw.org/demo/) is not working for all languages.

**Comment by RicardoUsbeck** [comment]
Hi, this is related to https://github.com/dice-group/AGDISTIS/issues/76 **maybe**. Can we have a redirect for http://agdistis.aksw.org/mag/mag or Diego, could you check please if MAG is running? Thanks!

**Comment by DiegoMoussallem** [comment]
@bigerl could you have a look at it?

**Comment by bigerl** [comment]
I pass it on to @lennartaustenfeld  
Could it be related to the hard-coded titan IP address?

**Comment by DiegoMoussallem** [comment]
well, the IP hasn't changed since its deployment. Therefore, I don't know. I guess it might be related to the new redirection, in the end, it is a guess

**Comment by RicardoUsbeck** [comment]
I think there is a multitude of proxies involved:

So according to https://github.com/dice-group/AGDISTIS_DEMO/blob/v2/src/main/java/org/aksw/mag/HomeController.java#L88 "http://akswnc9.informatik.uni-leipzig.de"

**But** According to the Chrome Inspect tab "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" to http://agdistis.aksw.org/mag/mag Thus, could you please check that the docker container on nc9 is running? 

When I curl it `curl --data-urlencode "text='The <entity>University of Leipzig</entity> in <entity>Barack Obama</entity>.'" -d type='agdistis' http://akswnc9.informatik.uni-leipzig.de:8113/AGDISTIS` it works. 

Note that http://agdistis.aksw.org/mag/mag gives a 405 manually checking it with GET 

Edit: Maybe the angular is broken? 
![image](https://user-images.githubusercontent.com/4354740/79876526-72839280-83eb-11ea-9adc-60b2bc644177.png)
What does MagResource refer to? I am no angular expert

**Comment by RicardoUsbeck** [comment]
Summoning @yamalight and @SimonBin to help me understand this issue. I have no clue, where it breaks. Please help 🙏

**Comment by yamalight** [comment]
@RicardoUsbeck here's the error that client gets (after long wait):
```
Type 
Exception Report

Message 
Request processing failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://akswnc9.informatik.uni-leipzig.de:8119/AGDISTIS": Connection timed out (Connection timed out); nested exception is java.net.ConnectException: Connection timed out (Connection timed out)

Description 
The server encountered an unexpected condition that prevented it from fulfilling the request.
```

seems like server can't reach `http://akswnc9.informatik.uni-leipzig.de:8119/AGDISTIS` for some reason? 🤔

**Comment by yamalight** [comment]
how is it deployed? can it be the same old docker network misconfig (when internal IPs clashed with existing uni network)? 🤔

**Comment by RicardoUsbeck** [comment]
Possible. Johnny deployed it with his magic on NC9. No idea how exactly (Prometheus, Ansible or even plain docker?). @DiegoMoussallem insights?

**Comment by RicardoUsbeck** [comment]
But http://akswnc9.informatik.uni-leipzig.de:8119/AGDISTIS can be reached 😕

**Comment by yamalight** [comment]
From the internet - yeah. My guess is - there's something off with routing between AGDISTIS server and nc9 🤔 
I'd first try CURL-ing NC9 from the server to see if that works.

**Comment by RicardoUsbeck** [comment]
Same 
![image](https://user-images.githubusercontent.com/4354740/79899698-70323000-840d-11ea-86ff-dc3bcb109db4.png)

So maybe really a docker network thing?

**Comment by yamalight** [comment]
That'd be the first suspect then 🤔 
Check the IP range and compare it to notes on [AKSW Wiki](https://wiki.aksw.org/private/infrastructure/docker)

**Comment by RicardoUsbeck** [comment]
Thanks for the pointers. I will take it to Slack and come back with a report.

**Comment by RicardoUsbeck** [comment]
@lennartaustenfeld Do you have access to aksw-slack?

**Comment by RicardoUsbeck** [comment]
Yes you do. Could you try to solve this issue please via the comments in aksw-slack/infrastructure? I can schedule a try to solve it only in 2 weeks from now

**Comment by RicardoUsbeck** [comment]
Just a short heads-up to @miguelwon We are on it, that is, in particular, @lennartaustenfeld is working on it.

**Comment by RicardoUsbeck** [comment]
Dear @miguelwon, thanks to @lennartaustenfeld, it should work again. Can you please try and close the issue if you are successful?

**Comment by miguelwon** [comment]
Ok, thanks for the follow-up.  Sorry, but still not working. I click and nothing happens. Might be related to the javascript. Two warnings in the console:

```
DevTools failed to load SourceMap: Could not load content for http://agdistis.aksw.org/demo/resources/js/angular.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://agdistis.aksw.org/demo/resources/js/angular-resource.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by RicardoUsbeck** [comment]
Can you use the demo at https://agdistis.demos.dice-research.org/ . We will redirect http://agdistis.aksw.org/demo/ to https://agdistis.demos.dice-research.org/  soon

**Comment by miguelwon** [comment]
Sure and thanks for the support.

**Comment by nguyennth** [comment]
Hello, thank you for providing a very nice demo. I could use it a while ago but I think now it's not running. I tried both of the provided links above, but none of them worked. Could you please have a look into it? Thank you again!
