### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by leileilin** [dice-group/AGDISTIS_DEMO#4]
hey men,
in command line usage,
why chinese mag not exist???
thank u.

**Comment by RicardoUsbeck** [comment]
Dear @leileilin ,

thanks for your interest in MAG/AGDISTIS. Can you describe your call in more detail? Are you asking the online demo?

Best regards
Ricardo

Summoning @DiegoMoussallem

**Comment by DiegoMoussallem** [comment]
@RicardoUsbeck it looks like our online demo is down as well as the Chinese instance. Could @vdanielupb or @bigerl help us with that? 

@leileilin we get back to you once it is online, but you can download the Chinese index and run it locally. Please have a look at https://hobbitdata.informatik.uni-leipzig.de/agdistis/dbpedia_index_2016-10/

**Comment by bigerl** [comment]
@leileilin should be up again. Checkout it out at http://agdistis.demos.dice-research.org/
